.github/workflows/generate-documentation.yml

Increase the timeout from 5 to 10 minutes as the site
deploy sometimes takes more than 5 minutes.
10 minutes is short enough to not be an issue in term of reactivity
And it is not that large so we will be able to detect any deployment time increase if it occurs,

chore(netlify): set client timeout to 10 minutes

---

scripts/convert_md_to_asciidoc.py

update the script to ignore the case during the regex substitution for tags `::: info`, `::: warning` and `::: danger`
example :
`::: warning` and `::: Warning` will be converted to `[WARNING]\n====\n`

feat(convert) : Make the substitution case insensitive

---

scripts/convert_md_to_asciidoc.py

* escape variable only in case of the page is portal-api.adoc or rest-api-overview.adoc to avoid warning message on Antora conversion.
expl : `{id_part2}` become `\{id_part2}`
* remove space located at end of http link in case the link is between \`
expl: `http://.../API/identity/membership/ ` become `http://.../API/identity/membership/`
closes #54

doc(convert) : manage variables + sanitize web link in code block

---

antora-playbook.yml
docs/migrate-from-old-documentation-site/migration-steps-put-the-site-live.adoc

Remove the .nojekyll file generation.
This was required by the github pages hosting that we have just removed, so no
need to generate this file anymore.
Remove reference to gh-pages from the documentation.

chore: update after gh-pages removal

---

.github/workflows/generate-documentation.yml
netlify.toml

* latest redirect for bonita and bcd as rewrite (proxy) instead of redicrect
* Bici redirect to labs/bici/
* javadoc/api to https://javadoc.bonitasoft.com/api/:splat

chore: update url redirect

---

.github/workflows/generate-documentation.yml

No more gh artifact download/upload.
We don't need to store it as we can download the published site as a zip from
the netlify dashboard.
No more need to run on 'pull_request'.
We don't need the full site as we have a preview for PR. The preview is managed
by a dedicated workflow which can be temporary tuned for specific needs.

chore: simplify the netlify deploys GitHub Workflow

---

netlify.toml

Update the defaults redirects to bonita latest.
Add specific redirects for some rename pages.

feat: update redirects for the legacy 6.x-7.2 bonita versions

---

antora-playbook.yml

Without quotes, a branche like 7.10 is transformed to 7.1 at build time. it's annoying :)

fix(branches): Use quotes for branches

---

antora-playbook.yml

This version is alpha and we don't want to display it.

feat: remove Bonita 2021.2 from the site

---

netlify.toml

Redirect to labs/latest/bici to ensure old urls are still working
This also requires https://github.com/bonitasoft/bonita-ici-doc/pull/130 to be merged.
closes #212

feat: redirect bici/latest

---

netlify.toml

In the oldest documentation site, some pages were generated to allow users to get an index point on some taxonomy categories.
Now, these pages didn't exist and links are broken. We decided at this moment to only add a redirect on `bonita/xx/_getting-started-tutorial` to `bonita/latest/tutorial-overview`.
This page is a good entry point for users who comes from a community site for example.
The test environment is available here: https://bonitasoft-test-redirect.netlify.app/bonita/latest/tutorial-overview
Nb: We can't use Antora `:page-aliases: _getting_started_tutorial.adoc` in content. At generation time, the `_` throw an error and page is not generated

feat: Add _getting Started redirect to tutorial-overview

---

README.adoc
docs/README.adoc
docs/architecture.adoc
docs/content/CONTRIBUTING.adoc
docs/migrate-from-old-documentation-site/doc-content-conversion-from-md-to-adoc.adoc
docs/migrate-from-old-documentation-site/migration-steps-put-the-site-live.adoc

We were using `Asciidoctor` when we refer to the markup language. In that case, `Asciidoc` must be used instead
Sources: https://docs.asciidoctor.org/home/
- AsciiDoc is a plain text authoring format (i.e., lightweight markup language) for writing technical content such as documentation, articles, and books"
- "Asciidoctor is the core AsciiDoc processor. It reads the AsciiDoc source, parses it into a document model, and converts it to a publishable format such as HTML using a converter."

doc: use 'AsciiDoc' wording instead of 'Asciidoctor' when appropriate

---

netlify.toml

Old version are redirected to BCD 3.4 and not latest (last version with BCD stack).

feat(bcd): Update old BCD redirects

---

antora-playbook.yml
build-preview.bash
scripts/generate-content-for-preview-antora-playbook.js

Aliases are now generating true http 301 instead of http 200 via http page; this
will be better for SEO.
Update the 'type' argument to enable it for preview.
closes #177 
The `_redirects` file is created is the same folder as the site content and is created for the production build.
The preview defaults don't change: redirects are managed by dedicated html pages (for file browsing or http servers without redirect capacities).
Redirects generation for preview tested locally with 
- preview creation:  `./build-preview-dev.bash --component bonita --branch 2021.2 --local-sources true --type netlify`
- then run dev server: `npm run serve`
**Note**: generated with `./build-preview-dev.bash --local-sources --force-production-navbar --use-all-repositories --type netlify` 
We currently have **606 …

feat: generate netlify redirects for alias

---

netlify.toml

Redirect all old versions and non version url to latest.
This reduces maintenance when releasing a new version.
I didn't test locally as changes are only replacements, but it's probably worth testing it once 😸

feat: simplify netlify redirects for BCD

---

netlify.toml

The former redirect haven't worked anymore since the introduction of Antora modules and some page renames.
This is because we use HTTP 200 for latest redirect, in this case, Netlify behaves as a proxy and the redirects generated by aliases were not used. So we got 404 errors.
Fix the redirects for the old `_getting_started page`: there is no alias for the previously targeted page that has been renamed/moved
Update the redirects for bonita 6.x-7.2 specific pages to avoid extra hoop.
See also #278 
Build preview for netlify: `./build-preview-dev.bash --local-sources --type netlify  --component bonita --branch 2021.2`
Netlify environment simulation: `npm run serve`
- general latest urls: localhost:8080/bonita/latest/getting-started-index --> --> …

fix(redirect): bonita 'latest' url also uses alias redirects

---

.github/workflows/commit-message-check-format.yml

We are only checking the PR title and description so we don't need to checkout (we are not considering the repository code here).

chore(wf): no checkout for PR convention checks

---

.github/workflows/publish-pr-preview.yml
.github/workflows/publish-production.yml

The previous path configuration were not trigger the workflows when changes occur in sub-folders.

chore: improve paths that trigger github workflows

---

.github/workflows/publish-pr-preview.yml
antora-playbook.yml

The failure-level option make Antora exits with a non-zero code when a message is logged with a severity error or higher. 
This allow us to make the build fail when a user try to commit an error in the documentation (invalid xref...)

feat(failure level): make the build fail on errors

---

.github/workflows/teardown-inactive-surge-deployments.yml

* Action is running each Saturday and kill inactive deployment for more than 1 month
Cover #315

chore: Teardown surge inactive

---

.github/workflows/publish-production.yml

* After enabled failedOnError antora attribute, we need a notification to know when the publish failed

chore: Send slack notification when publish failed

---

.github/workflows/publish-pr-preview.yml
build-preview-dev.bash
build-preview.bash

Remove the need of a specific script option, and rely on an environment variable
set by the CI provider. This simplifies the setting for local development.
- local: no impacts
- CI: see the preview 😸

chore: simplify the CI environment detection in the preview script

---

.github/workflows/propagate-doc-upwards.yml
scripts/propagate_doc_upwards.bash

So that when run from local env (which is the case when resolving conflict manually)
the script contains the right default values:
`git config merge.ours.driver true`

refactor(script): improve propagate-doc script

---

.github/workflows/publish-pr-preview.yml
.github/workflows/publish-production.yml

We currently have a dependabot update issue
> Dependabot can't parse your package-lock.json
> Dependabot failed to update your dependencies because there was an error parsing the package-lock.json found at /package-lock.json.
> Dependabot encountered the following error:
> Dependabot::DependencyFileNotParseable

chore: publish pr preview and to production on package.json change

---

docs/architecture.adoc
docs/documentation-components-and-versions.adoc

The configuration has been configured in the new DocSearch Crawler since February 2022, and no more by creating a Pull Request in the `algolia/docsearch-configs `repository.

doc: update link to DocSearch configuration

---

README.adoc
docs/configure-netlify-redirects.adoc
docs/content/CONTRIBUTING.adoc
docs/documentation-components-and-versions.adoc

Remove remaining links to Antora 2.3 except for the mardown to asciidoc migration as it applies to this antora version.
To simplify future maintenance, use an Asciidoc attribute to avoid duplicating the version as suggested few weeks ago by @benjaminParisel .
Some links that were redirected to renamed pages have been updated
**Notes**
Tested with the IntelliJ plugin and on GitHub Web.

documentation: reference the Antora 3 documentation

---

.github/workflows/publish-pr-preview.yml

The surge secrets is not available when the PR is created from a fork repository or by Dependabot.
The lack of secrets was generating an error when attempting to deploy. So, detect when the secrets
are available and only deploy in this case.
covers #361 
The configuration is taken from the bonita-doc repository
We have a lot of duplication across repository, I will investigate what can be done to reduce it as part of #361 and #239

chore: only publish the PR preview for repository members

---

.github/workflows/new_theme_bundle.yml
.github/workflows/update-theme-bundle.yml

Add a new workflow which:
- Is launched by a 'new_theme_bundle' Repository Dispatch event
- Update the Antora playbook with the new theme bundle url
- Create the PR
Covers (doc-site part) [Find a way to not be forced to store the Antora UI bundle in the repository](https://github.com/bonitasoft/bonita-documentation-site/issues/47)

chore: automate the ui bundle update

---

package-lock.json
package.json

netlify-cli from 10.3.1 to 10.5.0
js-yaml 4.0.0 to 4.1.0
Sill use a specific Antora version and don't allow auto updates
Tested locally: netlify cli with `npm run dev` (navigation and redirects are ok)

chore(deps-dev): bump dependencies and only allow patch auto updates

---

scripts/propagate_doc_upwards.bash

7.11 is now out of support, so the branch won't be updated anymore.
So no need to propagate changes to branches of next versions.

chore: drop bonita 7.11 content propagation

---

build-preview.bash
scripts/generate-content-for-preview-antora-playbook.js

Added new 'start-page' optional parameter to build-preview.bash
See https://docs.antora.org/antora/latest/playbook/site-start-page/ for details
closes #372

feat(start_page): New start-page parameter for build-preview script

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-setup/action.yml
.github/workflows/publish-pr-preview.yml

Introduce a dedicated action to build and publish the PR preview on surge
- it should be reused in documentation content repositories: see https://github.com/bonitasoft/bonita-doc/pull/2071
- it relies on an additional action from the `bonitasoft/actions` repository: https://github.com/bonitasoft/actions/releases/tag/v1.2.0. It provides more context for the surge-preview action: the preview url, know if the surge preview can be run (in particular during PR closed to prevent error when the surge domain doesn't exist)
covers #270 #361

chore: remove duplication in surge preview workflows

---

netlify.toml

Add test-toolkit redirects (latest and root redirects)
Other changes
- version order: consistent order from new to old for all components
- put redirects that won't get any update at the end
- improve comments and guidance (how-to add new redirects)
- remove extra spaces in configuration
I also proposed we stopped redirecting archived bonita versions to 'archives' and do it to 'latest'. It is in a dedicated commit (1cb7fe1bd417fd0a6faba16add3ec29243dfd5b8) so easy to rollback.
For people that have bookmarked bonita 7.4 that may be more convenient. But I understand that redirecting to archives provide them a way to get the former content.

refactor: reorganize Netlify redirects

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/workflows/publish-pr-preview.yml

The shared action also used in documentation content repository (see #270) now uses the new generic v1 tag of the `surge-preview-tools` action. We will then get the latest compatible changes automatically without having to update the version manually.
Latest changes in this action, see https://github.com/bonitasoft/actions/releases/tag/v1.3.0
> improve behavior when the surge token is not set (remove extra annoying warning logs that are not relevant)
In addition, the "pr preview" workflow is now also run when 'build-and-publish-pr-preview' changes.

chore(surge-preview-action): use the latest version of the surge-preview-tools action

---

docs/documentation-components-and-versions.adoc

Remove reference to past updates of the redirects as they are no more accurate.
Instead add a link to the the Netlify configuration file. It contains everything to understand how to create a redirect for the archived version.
closes #276

docs: update the "archive a version" procedure

---

.github/actions/build-and-publish-pr-preview/README.md
.github/actions/build-and-publish-pr-preview/action.yml
.github/workflows/publish-production.yml

Preview
- log the size of the site files
- upload an artifact when the site cannot be deployed to surge (fork repository, dependabot)
- add README to provide basic information about the action
Production: List the content of the generated site (files and size)
closes #403

ci: provide more information in the logs about the generated site

---

.github/workflows/propagate-doc-upwards.yml
scripts/propagate_doc_upwards.bash

Update the existing configuration
- scripts updated to manage both bcd and bonita
- the workflow runs both bcd and bonita updates
- add an option to not send slack notification when the workflow is run manually (useful for tests and debugging)
closes #410
Tested manually in dry-run
I didn't check the slack notifications.

ci: automate bcd doc content propagation from versions to versions

---

docs/content/CONTRIBUTING.adoc

Provide explicit example and don't only add links to the Antora documentation and existing work involving such links.
refs https://github.com/bonitasoft/bonita-doc/pull/2130
refs https://github.com/bonitasoft/bonita-doc/pull/2131

docs: improve cross version link documentation

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/workflows/build-all-site.yml
.github/workflows/build-pr-site.yml
.github/workflows/publish-pr-preview.yml
build-preview.bash
scripts/generate-content-for-preview-antora-playbook.js

* Always deploy pr-preview to allow contributors to see theirs updates
* Separate Build and deploy PR in two worflows
* Keep old build-and-pr-preview action but use a new param to ignore-error on demand
Cover https://github.com/bonitasoft/bonita-documentation-site/issues/399

ci: Separate preview and build in two worflows

---

.github/workflows/propagate-doc-upwards.yml

The Markdown syntax was incorrect, the name of the repository in the error message was surrounded by 2 asterisks (**) instead of being in bold.
Here is how the message looked like prior the fix:

ci(slack): fix bold style for "repository"

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/actions/build-setup/action.yml
.github/workflows/generate-static-doc.yml
.github/workflows/publish-pr-preview.yml
.github/workflows/publish-production.yml
README.adoc
build-preview.bash

Historically, the preview script was directly called by a lot of GitHub workflows. To avoid to duplicate the `npm ci` setup and ensure that Antora fetches sources, it was easier to do it in the script.
Now, all documentation content repositories use the GitHub actions provided by the bonita-documentation-site repository, so the extra settings can be managed by the shared actions.
This move provides a better separation of concerns. The script only focuses on generating the preview without managing special cases depending on the environment. The `npm ci` command is called directly in the `build-setup` internal action, where everybody expects to find it. This allows to introduce the usage of the GitHub cache for the npm dependencies, so we can expect fastest builds.
This also ensures …

chore: move special CI configuration out of the preview script

---

.github/workflows/build-pr-site.yml
.github/workflows/commit-message-check-format.yml
.github/workflows/generate-static-doc.yml
.github/workflows/manage-surge-deployments.yml
.github/workflows/propagate-doc-upwards.yml
.github/workflows/publish-pr-preview.yml
.github/workflows/publish-production.yml
.github/workflows/teardown-inactive-surge-deployments.yml
.github/workflows/update-theme-bundle.yml

The Ubuntu 22.04 runner is in GA and is stable, so we can safely use it.

ci: run all GitHub workflows on Ubuntu 22.04

---

docs/content/CONTRIBUTING.adoc

Previously, we advice to create alias only for page rename. We were missing move and delete.
We now provide more details and examples.

docs: improve the how-to about redirects/aliases

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/actions/log-built-site-details/action.yml
.github/actions/upload-pr-built-site-artifact/action.yml
.github/workflows/build-pr-site.yml
.github/workflows/publish-production.yml

This applies to the shared action, which is used in documentation content repositories and in this repository as well.
Also log the details of the generated files.
Introduce new shared actions to remove duplication
- upload the artifact of the site
- log built site details
Fix the `build-pr-site` workflow: it requires bcd 3.6, bonita 2022.1 to make xref validation pass

ci: upload artifact when building PR site

---

.github/actions/build-pr-site/action.yml
.github/workflows/build-pr-site.yml

Remove an extra if that isn't relevant. It related to surge preview.
Also update the `build-pr-site.yml` workflow: the bonita 2021.1 branch is now required for xref validation.

ci: simplify artifact upload in "build-pr-site" action

---

.github/workflows/commit-message-check-format.yml

Do not run when pushing new code (`synchronize` event) because the PR title doesn't change in this case. Run when reopening PR as the title may have changed while the PR was closed.
**Note**: detected with https://github.com/bonitasoft/bonita-doc/pull/2216

ci: limit runs of the 'pr-title-check' workflow

---

.github/actions/comment-pr-with-links/comments-with-url-links.js
.github/workflows/publish-pr-preview.yml

The actual comments template is ugly when a lot of files is updated in a PR
We suggest adding a checkbox to help users identify which file he has already check.
We replace the link by only the `moduleName/pageName`

feat: improve comments templating (for PR preview)

---

.github/actions/build-and-publish-pr-preview/action.yml

The new input allows to build and deploy the PR preview but also to validate xref.
Currently, this is needed for documentation component that have no xref to other components. See https://github.com/bonitasoft/bonita-labs-doc/pull/139
In the future, when `Antora Atlas` will be used (#326), all documentation content repositories will progressively do xref validation as part of the preview build.

ci(preview-action): add ignore-errors input

---

.github/workflows/commit-message-check-format.yml

This action better conforms to Conventional Commits and provides guidelines to help to fix wrong PR titles.
covers #422

ci: use bonitasoft/actions pr-title-conventional-commits

---

scripts/generate-content-for-preview-antora-playbook.js
test/documentation-content/apps-manager/1.0/antora.yml
test/documentation-content/apps-manager/1.0/modules/ROOT/pages/index.adoc
test/documentation-content/apps-manager/1.0/modules/ROOT/pages/page-01.adoc
test/documentation-content/apps-manager/1.0/modules/ROOT/taxonomy.adoc

* Only add Apps-manager-documentation on preview script
* We will add this component on "production" site only when the real name is choosing

feat: add apps-manager preview tooling

---

.github/actions/comment-pr-with-links/action.yml
.github/actions/comment-pr-with-links/comments-with-url-links.js
.github/actions/comment-pr-with-links/github.js

Since [this commit](https://github.com/bonitasoft/bonita-documentation-site/commit/c1190dab578dbd3931ce6b122e867f01b77d13de), we list the page edited to check in a comment to help the reviewer.
However in the first iteration we create and delete oldest comment at each triggered workflow.
With this PR, we just update the oldest comment if it's exist.

feat: Update comment instead create and delete

---

.github/actions/comment-pr-with-links/action.yml
.github/actions/comment-pr-with-links/comments-with-url-links.js

Improve the action that manages the PR comment about the details of the preview which is deployed to Surge:
* List deleted/renamed URL (on GitHub, a renamed file is detected as deleted and created with a new name)
* URL could be used to check if alias is exist and functional
* Only notify changes about AsciiDoc files (don't consider images for instance)
closes #463

ci(action): add deleted/renamed url in comment

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/actions/validate-pr-branch-name/action.yml
scripts/generate-content-for-preview-antora-playbook.js

Both the PR preview and build-site action now validates the name of the branch of the Pull Request.
Antora seems not using the branch when it contains special characters like parentheses. This introduces side effects that make the preview unusable (no content) and validation may failed.
As this is hard to diagnose by documentation content contributors, fail the workflow run if the PR branch is not valid for Antora and display an explicit error message.
Also escape all parameters passed to the `build-preview.bash` script to
avoid syntax error when it is executed.
closes #512 
This PR has been tested with the PR which detected the issue: https://github.com/bonitasoft/bonita-doc/pull/2309
The rexep has been tested with https://extendsclass.com/regex/a3fe16a
It maches
- fixMyProblem
- …

ci: validate the branch name of the pull request

---

scripts/propagate_doc_upwards.bash

This version is now out of support.

chore: stop propagating the content from bonita 2021.1

---

.github/actions/comment-pr-with-links/action.yml
.github/workflows/publish-pr-preview.yml
README.adoc

Before: When action is running when files doesn't match pattern the workflow is on error.
Now: We reverse the logic, and ignore file who doesn't respect the pattern given as input.
closes #511

ci(fix): update pattern for files preview comments

---

antora-playbook.yml
netlify.toml

Since bonita 2021.1 is out-of-support, we remove the latest version from site and generate static documentation for 7.8
Theses PR should be merged before this documentation-site PR.
:heavy_check_mark: Default branch on bonita-doc is now 2021.2
:heavy_check_mark: Algolia config is updated to remove 7.8

chore: remove bonita 7.8 version

---

docs/content/CONTRIBUTING.adoc
docs/documentation-components-and-versions.adoc

Introduce a new "Tips about the files organization" paragraph that includes the existing "Antora module" section and a new section about "file names".
Simplify the "component version" paragraphs: they were hard to follow and lacks of details. Only keep general information.

docs: improve the "contributors" documentation

---

lib/antora/versions-sorter-extension.js
scripts/generate-content-for-preview-antora-playbook.js
test/documentation-content/bcd/4.0/antora.yml
test/documentation-content/bcd/4.0/modules/ROOT/pages/index.adoc
test/documentation-content/bcd/4.0/modules/ROOT/pages/page-01.adoc
test/documentation-content/bcd/4.0/modules/ROOT/pages/page-02.adoc
test/documentation-content/bcd/4.0/modules/ROOT/pages/page-03.adoc
test/documentation-content/bcd/4.0/modules/ROOT/taxonomy.adoc
test/documentation-content/bcd/4.1-alpha/antora.yml
test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/index.adoc
test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-01.adoc
test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-02.adoc
test/documentation-content/bcd/4.1-alpha/modules/ROOT/pages/page-03.adoc
test/documentation-content/bcd/4.1-alpha/modules/ROOT/taxonomy.adoc
test/documentation-content/bcd/4.2-alpha/antora.yml
test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/index.adoc
test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-01.adoc
test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-02.adoc
test/documentation-content/bcd/4.2-alpha/modules/ROOT/pages/page-03.adoc
test/documentation-content/bcd/4.2-alpha/modules/ROOT/taxonomy.adoc
test/documentation-content/central/1.0/antora.yml
test/documentation-content/central/2.0/antora.yml
test/documentation-content/central/2.0/modules/ROOT/pages/index.adoc
test/documentation-content/central/2.0/modules/ROOT/pages/page-01.adoc
test/documentation-content/central/2.0/modules/ROOT/taxonomy.adoc

Previously, the custom Antora extension that sort the versions (to put alpha versions at the end of the list) fails to manage boolean prerelease attributes. It expected to find a string.
In addition
- search for alpha in the "display version" . This is not the way it should be configured but acts as a backup
- ignore case when searching for alpha. This handles `2023.2 Alpha` as well.
- enrich the "test content resources" to  better "test" the new Antora extension implementation (add new component versions)
This issue was spotted in https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/208

feat: handle antora prerelease boolean attribute

---

antora-playbook.yml
netlify.toml

Remove obsole BCD versions and publish BCD 4.
(To be merged once the target BCD doc content is ready)

feat(bcd): enable bcd 4 doc deployment

---

.github/workflows/propagate-doc-upwards.yml

The slack token was not correctly passed to the slack action (env variable instead of an action input).
The message has been reworked to be correctly displayed on Slack. 
closes #563
Full investigation and test of the fix done in 
The issue was introduced when switching to the `bonitasoft/actions` in #518

ci(push-production): fix slack configuration

---

.github/workflows/publish-production.yml
README.adoc
antora-playbook.yml
package-lock.json
package.json

* We used the Atlas extension to generate a site-manifest.json. This file will be zipped and pushed to the same place as the site.
* In the next step, we want to use these files to validate the xref linked in the content
This PR is inspired by https://github.com/bonitasoft/bonita-documentation-site/pull/575.

feat: Adding Atlas extension

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/workflows/generate-static-doc.yml
.github/workflows/publish-pr-preview.yml
build-preview.bash
scripts/generate-content-for-preview-antora-playbook.js

Use plural for consistency with other options.
This option is not supposed to be used outside of this repository. The shared GitHub Actions provide a dedicated input which must be used instead of the script option. So, this change won't have side effects in workflow of the documentation content repositories.

refactor(preview-script): fix typo in `ignore-errors`

---

scripts/propagate_doc_upwards.bash

* Remove content propagation for the 2021.2 version
Bonita-doc PR is ready [here](https://github.com/bonitasoft/bonita-doc/pull/2475)

chore: make bonita 2021.2 an "out-of-support" version

---

antora-playbook.yml
package-lock.json
package.json

Add Asciidoctor extension https://github.com/asciidoctor/asciidoctor-tabs
Related to https://github.com/bonitasoft/bonita-documentation-theme/pull/207

feat(extensions): add asciidoctor-tabs

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
.github/actions/build-setup/action.yml
.github/actions/comment-pr-with-links/action.yml
.github/actions/validate-pr-branch-name/action.yml

Bumped actions:
- actions/checkout: from v3 to v4
- actions/setup-node from v3 to v4
- actions/github-script v6 to v7
- tj-actions/changed-files from v35 to v40
@benjaminParisel I know you are working on improving the report about changed files in PR, this bump may impact your work. Let's talk about this!
- v36 https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#3600---2023-05-25
- v37 https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#3700---2023-06-23
- v38 https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#3800---2023-08-23
- v39 https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#3900---2023-09-04
- v40 https://github.com/tj-actions/changed-files/blob/main/HISTORY.md#4000---2023-10-26
[ANSWER] yes, see …

ci: bump actions called in composite actions

---

README.adoc

The link previously pointed to the SVG badge.

docs: fix link to "propage documentation" wf in README

---

.github/actions/build-pr-site/action.yml

Prepare the future by using the latest available alpha version.
Changelog: https://gitlab.com/antora/antora/-/blob/main/CHANGELOG.adoc#3-2-0-alpha-3-2023-12-19
Relates to #652

ci: use antora@3.2.0-alpha.3 when validating references

---

.github/actions/build-pr-site/action.yml

Prepare the future by using the latest available alpha version.
Changelog: https://gitlab.com/antora/antora/-/blob/main/CHANGELOG.adoc#user-content-3-2-0-alpha-4-2024-01-02
Relates to #657

ci: use antora@3.2.0-alpha.4 when validating references

---

.github/workflows/generate-static-doc.yml
.github/workflows/propagate-doc-upwards.yml

Use a token that has "workflow" permission when propagating documentation content.
This is required when updating the content of a workflow, otherwise an error occurs: `refusing to allow a Personal Access Token to create or update workflow '.github/workflows/push-content.yml' without 'workflow' scope`.
Use this token also in the "Generate static version" workflow to simplify maintenance (the token used here needs the same permissions).
The formerly used token has been removed from the configuration and the secrets.
According to the GitHub search, the `GH_PAT_TOKEN` secret was only used in the 2 workflows updated in this PR.

ci: update the secrets used in workflows

---

.github/actions/build-and-publish-pr-preview/README.md
.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/comment-pr-with-links/action.yml
.github/actions/upload-pr-built-site-artifact/action.yml
.github/workflows/publish-pr-preview.yml

Use the latest available and compatible versions
- actions/upload-artifact v3 to v4
- tj-actions/changed-files v40 to v42
This also ensures that the actions run with node 20 (remove warning about running actions with the deprecated Node 16 version).
In addition
- always upload artifacts to be able to test locally by downloading the content of the preview.
- postfix the name of the artifacts with the job id. This ensures to have unique name if the upload is done several times (name uniqueness is required by the new version of the upload-artifact action). This is needed for the doc-site PR as 2 previews are built (test and production contents)

ci: bump actions used in composite actions

---

.github/workflows/propagate-doc-upwards.yml

as it is easier to handle boolean inputs through check boxes

ci(propagate-content): use boolean inputs

---

test/documentation-content/bonita/v2021.2/antora.yml

**DISCLAIMER: this PR requires a new release of bonita-theme which includes https://github.com/bonitasoft/bonita-documentation-theme/pull/215**
Validate that the components can be hidden in navbar and in the component/version selector in all pages of a given component version.
This is done with a configuration in the component version descriptor.
Covers #689
Depends on https://github.com/bonitasoft/bonita-documentation-theme/pull/215

test: hide some components in pages of bonita 2021.2

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml
.github/workflows/commit-message-check-format.yml

The actions in this new version run with Node 20.
This removes deprecation warning in the GH Actions logs.

ci: bump bonitasoft/actions from v2 to v3

---

.github/workflows/commit-message-check-format.yml

There is no v4 version at the moment, as this version was mistakenly defined instead of v3.

ci: fix wrong action version in commit-message-check-format.yml

---

.github/actions/build-and-publish-pr-preview/README.md
.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/build-pr-site/action.yml
build-preview.bash
lib/antora/log-aggregated-component-versions-extension.js
scripts/generate-content-for-preview-antora-playbook.js

Let pass the git repo url to the preview script:
- Only valid for a branch preview for a component.
- This allows you to use an alternative URL to the one configured for the component, in particular to use a fork.
The "build-and-publish-pr-preview" and the "build-pr-site" (used for references validation) actions set this new argument to use the git URL of the branch of the PR
This ensures that the git URL of the repository whose the PR is originated from is used (fork or upstream repository).
Covers #402
Validation done for

ci: better support PR from fork for preview build and ref validation

---

.github/workflows/surge-build-preview-site.yml
.github/workflows/surge-build-preview-test.yml
.github/workflows/surge-deploy-pr-preview-site.yml
.github/workflows/surge-deploy-pr-preview-test.yml
.github/workflows/surge-deploy-pr-preview.yml

Previously, there was a single workflow to deploy 2 PR previews.
But the deployment URL depends on the job id, so the 2 deployments were done with the same URL whereas they should have their own.
Covers #686
Covers #700

ci: introduce 2 workflows to manage the PR deployments

---

.github/workflows/_reusable_surge-deploy-preview.yml
.github/workflows/surge-deploy-pr-preview-site.yml
.github/workflows/surge-deploy-pr-preview-test.yml

This was not working as the 2 workflow used to deployed called the same reusable workflow that deployed to the same URL for the 2 environments. This was because the URL is computed using the job id of the reusable workflow.
So for "test" deployment, duplicate the logic of the reusable workflow to have a dedicated URL.
In the "deploy" reusable workflow, use a shorter job id. It is used to compute the URL of all deployments. A shorter name ensure that we don't try to generate a too large URL subdomain.
The PR comment relative to the changes will be managed by a dedicated workflow in the future for a better separation of concerns, to simplify the maintenance and to make things more explicit. So remove the related steps (that was still a work in progress) from the reusable workflow in charge …

ci: make PR surge deployments work with both site and test

---

.github/workflows/_reusable_pr-comment-list-changes.yml

* In reusable, we need to checkout the docSite branch to find our reusable workflow
covers #700

ci: Adding missing checkout step for reusable worklow

---

.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml

*  Adding new forbidden pattern to chuseck:  https://api-documentation.com, we don't want add this to our documentation because we have antora variable to do this

ci(antora-check): forbid API documentation URL

---

build-preview.bash

Log the version Antora that is used.
This lets validate that we don't use the same Antora version when building the site and when checking the references.
Check references
```
Use Antora version:
@antora/cli: 3.2.0-alpha.4
@antora/site-generator: 3.2.0-alpha.4
```
Build site
```
Use Antora version:
@antora/cli: 3.1.7
@antora/site-generator: 3.1.7
```

chore: improve logs in the preview script

---

.github/workflows/_reusable_surge-deploy-preview.yml
.github/workflows/surge-deploy-pr-preview-test.yml

We currently have rate limit errors when deploying doc PR with surge.
Try using the `BONITA_CI_PAT` instead of `GITHUB_TOKEN` to avoid rate limit error

ci(surge-deploy): try to limit API rate limit errors

---

.github/workflows/_reusable_surge-deploy-preview.yml

Provide a way to investigate what we try to deploy to surge.
covers #741

ci(surge-preview): archive the preview site deployed to surge

---

.github/workflows/_reusable_surge-build-preview.yml
.github/workflows/_reusable_surge-deploy-preview.yml
.github/workflows/surge-deploy-pr-preview-test.yml

Previously, this wasn't set in `dawidd6/action-download-artifact` so the
action was doing a search to retrieve the artifact.
It was using default search parameters, so it skip workflow runs for PR
from forks, and always considered the latest run of the workflow.
So, when several PR was opened simultaneously, a wrong artifact could be
retrieved.
In addition, don't run the deployment workflow if the build step failed.
Fix the fix, the deployment would fail because no artifact is available for download.
Fixes #741
Validated with https://github.com/process-analytics/github-actions-playground/pull/363#issuecomment-2205176295
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
> A workflow run is …

ci(surge-deploy): get artifact from the specific workflow run

---

.github/dependabot.yml

Previously, the PRs were all rebased when the master branch changed. This triggered a lot of workflow runs, and new rebase when new PR was merged again.
We prefer doing the PR rebase/update at our own pace and reduce the number of runs.

chore(dependabot): do not rebase PR when the base branch is updated

---

.github/actions/comment-pr-with-links/comments-with-url-links.js

* when the updated file is in ROOT module, the preview link contains // before this PR
An example could be fine here => https://github.com/bonitasoft/bonita-doc/pull/2794

fix:  Path root for file udpate in Root module

---

.github/actions/build-pr-site/action.yml

Changelog: https://gitlab.com/antora/antora/-/blob/main/CHANGELOG.adoc?ref_type=heads#user-content-3-2-0-alpha-6-2024-07-23

ci(validate ref): bump antora from 3.2.0-alpha.5 to 3.2.0-alpha.6

---

.github/workflows/propagate-doc-upwards.yml

Use the dedicated bonitasoft action to set commiter information and enforce commit signing

ci: sign commit when propagating doc content upwards

---

antora-playbook.yml

All branches of the documentation content repositories have been reviewed and fixed to no longer generate warnings. Enabling this feature will prevent from introducing new warnings without being notified.
This has no impact on preview builds: they already configure the log level that make the build fail.
Closes #776

ci(production): fail the Antora build on warnings

---

.github/workflows/teardown-inactive-surge-deployments.yml

The action didn't work after the release of surge 0.24.
The new version 0.1.4 of the action fixes the problem.
Closes #771
✔️ Tested with an intermediate commit (master branch): see https://github.com/bonitasoft/bonita-documentation-site/issues/771#issuecomment-2304415900
ℹ️ Tested with the branch of this PR https://github.com/bonitasoft/bonita-documentation-site/actions/runs/10525237283/job/29163605502. There is no deployment to teardown, so this doesn't validate the fix
```
Download action repository 'adrianjost/actions-surge.sh-teardown@v1.0.4' (SHA:f8c2503a1cae5afc57859b9c6afc3fabdbfde027)
...
Run adrianjost/actions-surge.sh-teardown@v1.0.4
DryRun: false
search for projects that match /[1-9]+ month.? ago/i
found 0 projects for teardown
```
Notice that the commit of the v0.1.4 tag is …

chore(gha): bump adrianjost/actions-surge.sh-teardown from 1.0.3 to 1.0.4

---

.github/workflows/update-theme-bundle.yml

Signing commits is a mandatory check in the GitHub rulesets for the default branch of the repository.

ci: sign commits in the PR updating the theme

---

.github/workflows/update-theme-bundle.yml

The committer must be set when calling peter-evans/create-pull-request.
See  https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#gpg-commit-signature-verification

ci: sign commit when creating the PR to update the theme bundle

---

.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml

This check is performed in the PRs of an existing document content repository.
It is recommended to use the AsciiDoc page attribute instead.
Such links were present in the bonita content and had been replaced by AsciiDoc attribute in https://github.com/bonitasoft/bonita-doc/commit/71764d964f78afa36240e06a672d7e811584b9c4

ci: prohibit direct links with the CSC in the content of documentation

---

.github/workflows/_reusable_pr-antora-content-guidelines-checker.yml

This check is performed in the PRs of an existing document content repository.
It is recommended to use the AsciiDoc page attribute instead.
This PR continues the work stared in #813

ci: prohibit direct links to new CSC in documentation

---

.github/workflows/_reusable_pr-comment-list-changes.yml
.github/workflows/_reusable_surge-build-preview.yml
.github/workflows/_reusable_surge-deploy-preview.yml

The current job id is used by the surge-preview to build the deployment URL. This URL is used to build the site and to check its validity. However, it was not the same as the actual one used for deployment as the job id was not the same as in the workflow doing the deployment.
In addition, the former job id was longer so in repository with a long name (like for BCD), the URL was detected as invalid (because it was too long).
The workflow now uses the same job id as in other workflow, which fix all issues.
This should fix error like in https://github.com/bonitasoft/bonita-continuous-delivery-doc/actions/runs/13633276913/job/38105740681?pr=228
```
Run bonitasoft/actions/packages/surge-preview-tools@v3
Surge cli version: v0.24.6
Find PR number: 228
Error: The computed surge subdomain is too …
```

ci: rename job id of "_reusable_surge-build-preview.yml"

---

.github/workflows/_reusable_surge-build-preview.yml
scripts/generate-content-for-preview-antora-playbook.js

The PR link was not always set, particularly when generating a PR preview comprising a single branch.
It is now always set, regardless of the type of preview (single branch, one branch per repository, ...) that is generated.

fix: display the link to PR in the preview

---

.github/workflows/check-links.yml
scripts/htmltest/htmltest_bonita-documentation-site.yml

Ignore some site to be more resilient and avoid false positives.
When the scheduled task runs  (at 5 am UTC) with the configuration of the current master branch, GitHub returns a lot of HTTP 429 error when checking the URL to the source code like in the following extract 👇🏿 (full logs: 
[check-links-analysis-c3e15a65361b496303e0cf5c9fe49d2f3b0c861a.zip](https://github.com/user-attachments/files/20208840/check-links-analysis-c3e15a65361b496303e0cf5c9fe49d2f3b0c861a.zip)).
This is not reproduced when running with workflow_dispatch or pull_request during the work day.
```
Non-OK status: 429 --- bonita/2024.2/identity/user-authentication-overview.html --> https://github.com/bonitasoft/bonita-engine/blob/10.1.0/bpm/bonita-web-server/src/main/java/org/bonitasoft/console/common/server/login/servl …
```

chore: update configuration of htmltest

---

.github/workflows/_reusable_surge-build-preview.yml

There is no need to run this workflow when the PR is closed. When the PR is closed, the site is left as it is or it is undeployed.
So, there is no need to build the site, and the whole workflow execution can then be skipped in this case.

ci: simplify the reusable workflow that builds the surge preview

---

.github/workflows/_reusable_nightly_compress_image.yml
.github/workflows/compress_nightly.yml

This pull request introduces workflows to automate image compression and streamline the process of creating pull requests for compressed images. The changes include a reusable workflow for nightly image compression and a specific workflow to trigger this process on demand or via a weekly schedule.
* [`.github/workflows/_reusable_nightly_compress_image.yml`](diffhunk://#diff-caa26ea82914fe2a941aa13a18ae941614c70f7204282e5970aa6a9103b16e91R1-R42): Added a reusable workflow that compresses images and creates a pull request if any images can be compressed. It supports inputs for pull request title and branch name, and uses the `calibreapp/image-actions` and `peter-evans/create-pull-request` actions.
* [`.github/workflows/compress_nightly.yml`](diffhunk://#diff-ad6e0ff0889cd262d1442f04a8d83cd81 …

feat: Add reusable workflow for nightly image compression

---

.github/workflows/_reusable_compress_images_nightly.yml
.github/workflows/compress_nightly.yml

Apply return found on https://github.com/bonitasoft/bonita-doc/pull/3049:
* Homogenise the calibreapp/image-actions to use the same commit
* Rename the nightly reusable action

feat: Adapt reusable workflow for nightly image compression
