bonitasoft/bonita-documentation-site

.github/workflows/generate-documentation.yml

Build the site and store it as artifact result on:
* manually trigger
* open a PR based on the master
* push on the master branch (or merge PR)
For now, we don't push each time on gh-page. Will do it on another PR.
covers #5

ci(generateDoc): Action to build the site

---

.github/workflows/generate-documentation.yml

* trigger on push or with worflowDispatch event
* Only trigger on master branch
Covers #5

Push to gh page on push

---

LICENSE
package.json

Use 'GPL v2 or later' to follow Bonitasoft guidelines.
For the license in 'package.json', the id taken from spdx.org/licenses
covers #10

chore(license): add license to repository

---

.github/workflows/generate-documentation.yml

Commit messages : 
- **push on master branch**: deploy <commit> as today
- **workflow_dispatch manual**: don't set the doc component info --> deploy <commit> from manual request
- **workflow_dispatch from doc component**: pass the info in the event --> deploy <component> <branch> update
Closes #45

chore(ci): custom gh-pages commit message

---

.gitignore
README.adoc
antora-playbook.yml
package-lock.json
package.json
scripts/generate-local-sources-antora-playbook.js

Generate an Antora Playbook from the regular one and change the content sources
configuration.

chore(playbook): allow to use locally clone document content repository

---

antora-playbook.yml

**WIP**
- rebase needed
- Needs doc content branch to be merged in bonita-doc or renamed
Remaining works
- convert notes, warnings, ...
- fix asciidoctor warnings

feat(bonita): Add 7.3 documentation

---

antora-playbook.yml

chore: plug google analytics test

---

antora-playbook.yml

concurrence to thefurets.com ;)

fix(components): restore doc modules in antora playbook

---

.github/workflows/generate-documentation.yml
antora-playbook.yml
netlify.toml

- Add step for GH to deploy on netlify
- Setup first redirects
close #117

feat(Netlify): Add step in GH to deploy built site on Netlify

---

.github/workflows/generate-documentation.yml

doc(ga): point google analytics to netlify

---

antora-playbook.yml

feat: update the site url

---

docs/migrate-from-old-documentation-site/doc-content-conversion-from-md-to-adoc.adoc

We now have a python script, so some steps are not required anymore

doc: update the md to adoc conversion procedure

---

.github/workflows/generate-documentation.yml

* add repository_dispatch trigger that listens to `source_documentation_change` event.
* update condition to trigger a build of doc site
covers #167

chore: add repository_dispatch trigger

---

antora-playbook.yml

* Config update is necessary after branches renaming

chore: update config after branches renaming

---

.github/workflows/generate-static-doc.yml

* Put BonitaBPM - Archived as default title

ci: set default title for static generation

---

antora-playbook.yml
netlify.toml

- Antora playbook target all principal branches for Bonita

Migration: Update Bonita branches

---

.github/workflows/generate-documentation.yml
antora-playbook.yml

Only Merge when we are ready to go into production
Covers #20 
#141 
#139

ci: Last update to go in production

---

netlify.toml

feat: redirect preview urls to the primary domain

---

.github/workflows/publish-production.yml

chore: rename gh wf that publish to production

---

docs/content/CONTRIBUTING.adoc

fix: Source code support: add missing link

---

antora-playbook.yml
netlify.toml

- Remove branch 7.5 from the documentation
- - Update redirects

core(release): release 2021.2

---

docs/configure-netlify-redirects.adoc

Add a step by step procedure to ensure that everybody will be able to test redirects easily.

doc: Improve test redirect procedure

---

netlify.toml

feat: add redirects for 'asciidoc-templating' groovydoc

---

docs/content/CONTRIBUTING.adoc

* add Troubleshooting section formatting guidelines

doc: Update CONTRIBUTING.adoc

---

.github/workflows/propagate-doc-upwards.yml
README.adoc
docs/documentation-components-and-versions.adoc
scripts/propagate_doc_upwards.sh

* Add action (with cron all night)
* Use bash script comes from internal-tools
* Update documentation
Covers #292

feat(docPropagation): Create action to propagate doc

---

docs/documentation-components-and-versions.adoc

Reword and add information about updating the preview script.

doc: improve 'components and versions' how-to

---

.github/workflows/publish-pr-preview.yml

test-toolkit@1.0 now requires bonita@2022.2

chore: update branches used to generate the PR preview

---

.github/dependabot.yml

The dependabot time is set to 5am (instead of a random time by default)

chore(dependabot): Set dependabot check on fridays 5am

---

docs/content/CONTRIBUTING.adoc

For new users, specify where data can be found regarding version and component name.

docs(contributing): add details regarding version and component name 

---

antora-playbook.yml
netlify.toml

Remove the 7.7 doc for archival (as the 7.15 is releasing)

feat(release): remove the bonita 7.7 doc

---

docs/content/CONTRIBUTING.adoc

Covers https://github.com/bonitasoft/bonita-documentation-theme/issues/129

doc(bonita_editions): documented rules to follow to specify Bonita editions restrictions

---

docs/content/CONTRIBUTING.adoc

docs(contributing): make the alias examples consistent

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/comment-pr-with-links/action.yml
.github/actions/comment-pr-with-links/comments-with-url-links.js
.github/actions/comment-pr-with-links/github.js

- Create a composite GitHub action
- Adding links for created/updated files
- Adding warning if some file is deleted or renamed on a PR
Covers #373 
Covers #463

feat: comments PR with info for reviewers

---

.github/actions/build-and-publish-pr-preview/action.yml
.github/actions/comment-pr-with-links/comments-with-url-links.js
.github/actions/comment-pr-with-links/github.js

* fix message templating to add checkbox
* adding a commentId to retrieve comment to delete

fix: Delete oldest comment and improve template

---

test/documentation-content/apps-manager/1.0/antora.yml
test/documentation-content/bcd/3.4/antora.yml
test/documentation-content/bcd/3.5/antora.yml
test/documentation-content/cloud/latest/antora.yml
test/documentation-content/test-toolkit/1.0/antora.yml

* Since "Bonita" is going to be removed from component title in documentation, we need to keep up-to-date our "tests"
Closes #482

chore: remove Bonita on component title

---

.github/workflows/propagate-doc-upwards.yml
.github/workflows/publish-production.yml

* Adapt slack message
Close https://github.com/bonitasoft/bonita-documentation-site/issues/465

ci: use notify-slack common action

---

antora-playbook.yml
test/documentation-content/bcd/4.0/modules/ROOT/pages/index.adoc

Added font-awesome use sample.
Depends on https://github.com/bonitasoft/bonita-documentation-site/pull/554

feat(icon): add font-awesome samples

---

README.adoc
docs/content/CONTRIBUTING.adoc

docs: explain partial build and xref validation

---

docs/content/CONTRIBUTING.adoc

Improve example based on recent feedback
Feedback from https://github.com/bonitasoft/bonita-continuous-delivery-doc/pull/212

docs: better explain how to disable attribute substition

---

antora-playbook.yml
netlify.toml
scripts/propagate_doc_upwards.bash

* The bonita-doc PR is done on: https://github.com/bonitasoft/bonita-doc/pull/2463

chore: add bonita 2024.1 version

---

.github/workflows/generate-static-doc.yml

Provide more explicit guidance for users.
It is based on feedback collected while archiving the documentation of Bonita 7.9.

ci: improve user description in "Generate Static Documentation"

---

docs/content/CONTRIBUTING.adoc

It's decided to refer only Subscription editions since 2023.2 Bonita version instead of Enterprise, Performance, and Efficiency edition

docs: Update section about adminition edition

---

antora-playbook.yml
lib/antora/log-aggregated-component-versions-extension.js
lib/antora/versions-alias-extension.js

The sources (providing the repository URL and ref, several elements can be used) are only logged when the debug level is enabled to prevent from generating too many logs.
With test data.
<details>
<summary>Log level DEBUG</summary>
<pre>
[14:44:35.185] INFO (bonita-log-aggregated-component): Discovered the following component versions
[14:44:35.188] INFO (bonita-log-aggregated-component): name: bcd, version: 3.4, files: 5
[14:44:35.189] DEBUG (bonita-log-aggregated-component): sources: [{"url":"https://github.com/bonitasoft/bonita-documentation-site.git","refname":"chore/log_component_version_during_processing"}]
[14:44:35.189] INFO (bonita-log-aggregated-component): name: bcd, version: 3.5, files: 5
[14:44:35.190] DEBUG (bonita-log-aggregated-component): sources: …

chore: add an antora extension to log aggregated component

---

antora-playbook.yml
netlify.toml
scripts/propagate_doc_upwards.bash

Depends on https://github.com/bonitasoft/bonita-doc/pull/2651

feat: remove bonita 7.10

---

.github/workflows/_reusable_surge-deploy-preview.yml

ci: remove extra inputs in the reused deploy preview wf

---

.github/actions/comment-pr-with-links/comments-with-url-links.js

A test is open on bonita-doc to validate this update https://github.com/bonitasoft/bonita-doc/pull/2793
Close https://github.com/bonitasoft/bonita-documentation-site/issues/750

feat: Support link generation for page declare in submodule

---

antora-playbook.yml
netlify.toml

* Add redirect for Bonita 7.11
* remove the 7.11 version

feat: remove bonita 7.11

---

.github/workflows/_reusable_surge-build-preview.yml
build-preview.bash
scripts/generate-content-for-preview-antora-playbook.js

* The v1.23.0 version of theme, allow us to display the prLink in nonProduction mode
close https://github.com/bonitasoft/bonita-documentation-site/issues/584

feat: Allow to navigate from the live preview to the PR

---

antora-playbook.yml
package-lock.json
package.json

* Since latest version of theme (v1.25.0), we can use the asciinema-extension

feat:  Activate Asciinema extension

---

.github/workflows/check-links.yml
antora-playbook.yml
scripts/propagate_doc_upwards.bash

Related to https://github.com/bonitasoft/bonita-test-toolkit-doc/pull/66

chore(release): new test toolkit 3.1
